#!/bin/bash
make clean
make grammar

FS=(`cd tests; ls *.in | sed 's/.in//'; cd ..`)

NPASS=0
NTOT=${#FS[@]}
for T in ${FS[@]}; do
    cp tests/$T.in input
    python3 main.py input
    riscv64-unknown-elf-gcc output.s
    qemu-riscv64 a.out
    echo $? > output
    echo $T "================================"
    diff -qZ tests/$T.ans output && NPASS=$((NPASS+1))
done
echo $NPASS / $NTOT
